
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 20 04:53:15 CDT 2021
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pal_del = 41;
  public static final int Par_Der = 10;
  public static final int Tabulacion = 2;
  public static final int Coma = 15;
  public static final int Pal_def = 36;
  public static final int Pal_except = 24;
  public static final int Dos_Punt = 14;
  public static final int Num_Float = 53;
  public static final int Num_Int = 52;
  public static final int Pal_as = 35;
  public static final int Cor_Der = 12;
  public static final int Variable = 50;
  public static final int Pal_class = 27;
  public static final int Pal_pass = 21;
  public static final int Ident = 51;
  public static final int Num_Imag = 54;
  public static final int Oper_Log = 4;
  public static final int Pal_assert = 40;
  public static final int Oper_AsigArit = 8;
  public static final int Punto = 16;
  public static final int Oper_Bol = 6;
  public static final int Punt_Coma = 13;
  public static final int Pal_None = 22;
  public static final int Pal_for = 32;
  public static final int Pal_break = 23;
  public static final int EOF = 0;
  public static final int Oper_Arit = 3;
  public static final int Pal_not = 43;
  public static final int Oper_Asig = 7;
  public static final int Pal_continue = 31;
  public static final int error = 1;
  public static final int Pal_return = 30;
  public static final int Pal_from = 37;
  public static final int Pal_await = 18;
  public static final int Pal_lambda = 33;
  public static final int Pal_else = 19;
  public static final int Pal_is = 29;
  public static final int Par_Izq = 9;
  public static final int ERROR = 56;
  public static final int Pal_while = 39;
  public static final int Pal_finally = 28;
  public static final int Pal_global = 42;
  public static final int Pal_in = 25;
  public static final int Pal_async = 45;
  public static final int Pal_import = 20;
  public static final int Pal_if = 47;
  public static final int String = 55;
  public static final int Pal_nonlocal = 38;
  public static final int Oper_Rel = 5;
  public static final int Pal_try = 34;
  public static final int Cor_Izq = 11;
  public static final int Pal_print = 49;
  public static final int Pal_raise = 26;
  public static final int Pal_elif = 46;
  public static final int Comilla = 17;
  public static final int Pal_yield = 48;
  public static final int Pal_with = 44;
}

